export const allProducts = [
  {
    id: 2,
    name: "Boubou Élégance Ébène",
    price: 159,
    originalPrice: 200,
    image: "../../public/images/rb-shop2.png",
    category: "Boubou",
    rating: 4.5,
    isNew: false,
    isOnSale: true,
    description: "Un boubou noir intense aux finitions subtiles pour une allure raffinée. L’élégance à l’état pur, parfaite pour les grandes occasions.",
    features: ["Tissu fluide satiné", "Broderies ton sur ton", "Col mao traditionnel", "Manches longues évasées"],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Noir", "Noir & Argent", "Bleu Nuit"],
    care: "Lavage à la main ou à sec",
    delivery: "Livraison gratuite sous 5 jours"
  },
  {
    id: 3,
    name: "Boubou Prestige Saphir",
    price: 199,
    originalPrice: 245,
    image: "../../public/images/rb-shop3.png",
    category: "Boubou",
    rating: 5,
    isNew: true,
    isOnSale: false,
    description: "Un bleu profond et des broderies fines : ce boubou évoque la noblesse des traditions africaines dans un esprit résolument moderne.",
    features: ["Tissu riche et fluide", "Broderies contrastées", "Col structuré", "Coupe ample et confortable"],
    sizes: ["S", "M", "L"],
    colors: ["Bleu Saphir", "Gris & Bleu", "Turquoise"],
    care: "Nettoyage à sec uniquement",
    delivery: "Livraison express en 48h"
  },
  {
    id: 4,
    name: "Boubou Impérial Blanc Cassé",
    price: 175,
    originalPrice: 215,
    image: "../../public/images/rb-shop4.png",
    category: "Boubou",
    rating: 4.8,
    isNew: true,
    isOnSale: true,
    description: "Pureté et prestige réunis dans ce boubou blanc cassé orné de motifs brodés à la main. Un classique indémodable pour briller.",
    features: ["Coton épais premium", "Broderies ivoire", "Encolure arrondie", "Coutures renforcées"],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Blanc Cassé", "Ivoire", "Beige Doré"],
    care: "Lavage délicat conseillé",
    delivery: "Livraison gratuite sous 3 jours"
  },
  {
    id: 5,
    name: "Boubou Royal Émeraude",
    price: 209,
    originalPrice: 250,
    image: "../../public/images/rb-shop5.png",
    category: "Boubou",
    rating: 5,
    isNew: false,
    isOnSale: false,
    description: "Une teinte émeraude saisissante pour un boubou d’une grande prestance. Conçu pour les moments d’exception.",
    features: ["Tissu satiné de luxe", "Broderies argentées", "Coupe droite élégante", "Col officier"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Émeraude", "Vert & Or", "Vert Nuit"],
    care: "Nettoyage à sec recommandé",
    delivery: "Livraison offerte sous 4-6 jours"
  },
  {
    id: 6,
    name: "Boubou Sahara Sable Doré",
    price: 149,
    originalPrice: 180,
    image: "../../public/images/rb-shop6.png",
    category: "Boubou",
    rating: 4.6,
    isNew: false,
    isOnSale: true,
    description: "Inspiré des dunes du désert, ce boubou aux tons chauds et naturels respire la tradition et la douceur.",
    features: ["Coton léger respirant", "Tons sable et or", "Coupe ample traditionnelle", "Col rond travaillé"],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Sable Doré", "Caramel", "Terracotta"],
    care: "Lavage à froid recommandé",
    delivery: "Livraison gratuite sous 5 jours ouvrés"
  }
];
